### ISSUE TITLE
🐛 VSCode extension creates dead Explorer links in function hovers

### ISSUE THREAD

**Issue by laulauland** [autometrics-dev/vscode-autometrics#64]
### Environment information

```plain text
TypeScript Autometrics
===
VSCode Info
Version: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:57:59.134Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

### What happened?

Project:
```
.
├── dist
│  ├── routes.js
│  ├── routes.js.map
│  ├── server.js
│  ├── server.js.map
│  ├── util.js
│  └── util.js.map
├── package-lock.json
├── package.json
├── README.md
├── rome.json
├── src
│  ├── routes.ts
│  ├── server.ts
│  └── util.ts
└── tsconfig.json

```

Repro:
1. Set the graph preferences to Autometrics Explorer
2. In `server.ts` when hovering over an Autometrics instrumented function VSCode generates a tooltip with the following link: `http://localhost:6789/explorer/#/functions/details/handleGetAllUsers/requestRate`

### Expected result

This is the correct link it should generate, however:

`http://localhost:6789/explorer/#/functions/details/m/%2Fdist%2Fserver.js/handleGetAllUsers`

Note the `dist` in the module name missing.

In my mind there are two options:
1. Either the extension needs to correctly figure out the module name (might be hard in different languages)
2. Autometrics Explorer should handle links with just the function names: redirect to the complete URL with the module name or if there are multiple functions with the same names in different modules - show an intermediary selector screen

**Comment by flenter** [comment]
The vscode is relying on the @autometrics/typescript-plugin to provide function/module information. However the typescript plugin only ever returns the function name: https://github.com/autometrics-dev/autometrics-ts/blob/main/packages/typescript-plugin/src/index.ts#L79

**Comment by flenter** [comment]
If explorer finds multiple results for a single function name it should redirect you to function page without a module name specified (which should result in a graphs with multiple lines where each line matches the function name but has a different module value)

**Comment by laulauland** [comment]
Ah I wasn't clear - the issue was that the page would load but it wouldn't show any data for the function. Will refile this issue where appropriate.
